### ISSUE TITLE
Project tracking

### ISSUE THREAD

**Issue by shreevatsa** [shreevatsa/ambuda#30]
After reading/watching [“Coping strategies for the serial project hoarder” by simonw](https://simonwillison.net/2022/Nov/26/productivity/) (and also skimming of his earlier stuff like [this](https://simonwillison.net/2022/Jan/12/how-i-build-a-feature/)/[this](https://simonwillison.net/2022/Oct/29/the-perfect-commit/)/[this](https://twitter.com/simonw/status/1458484154341859334)), I'm inspired to try out the approach here. Namely:

- “issue driven development”, where everything is done via GitHub issues with comments of you talking to yourself, and 
- leave everything documented, in a state where you can walk away at any point, and thus avoid guilt which is what kills personal projects.

**Comment by shreevatsa** [comment]
(I tried this in #31 and it was satisfying!)

**Comment by shreevatsa** [comment]
I think this is mostly done/underway, and I'm getting the hang of "issue-driven development" or something like it, but instead of closing this issue I'll use this comment to keep track of the project (GitHub projects doesn't support nesting):

- [x] #31 
- [ ] #32 Bookchop
  - [x] #33 
    - [x] #35 
      - [x] #36 
    - [x] #37
    - [x] #38 
  - [x] Editor basic usability
    - [x] #40
    - [x] #42
    - [x] #39
    - [x] #41
  - [x] #43 
    - [x] #48
    - [x] #57 
  - [x] #46 
    - [x] #58
    - [x] #59 
  - [x] #60 
    - [x] #61 
- [ ] #49 (children tracked separately at that issue, not expanded here)
- [ ] Backlog (not currently bothering me)
  - [ ] #34 
  - [ ] #44 
  - [ ] #45 
  - [ ] #47 
  - [x] #56
  - [ ] #62 
  - [ ] #63

**Comment by kvchitrapu** [comment]
@shreevatsa, do you plan to preserve the text formatting from the source? I don't know if it is possible. Even the basic formatting like titles, headings, bullets/numbering, paragraphs, and text interlaced with English and an Indic language will be a good step.

**Comment by shreevatsa** [comment]
@kvchitrapu Yes (sort of). All of that is possible (think of what can be represented in say Google Docs, or see the demo editor on the front page of https://prosemirror.net/). The goal, though, is not so much to exactly preserve the formatting of the source, but whatever we want to represent conceptually/semantically in the text for Ambuda: e.g. in a commentary, instead of "bold" we could say "this is the pratīka" (the first word repeated from the source text, usually printed in bold), and it happens to render as bold in our editor. So the same thing, but possibly with more structural information attached.
